mysql: #DB
  host: localhost
  port: 3306
  user: root
  pass: pass
  db: bjp

price: #1チップ当たりの賭け金の設定
  enable: true #オンにするかオフにするか
  min: 1000.0 #最低金額
  max: 100000.0 #最高金額

gameconfig:
  spdrawchance: 20.0
  coin: 10
  bet: 2
  round: 3
  clocktime: 30



cardconfig:
  spcardmaterial: SPRUCE_SAPLING
  cardmaterial: SPRUCE_SAPLING
  invisiblecsm: 12

  cardcsm:
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    - 8
    - 9
    - 10
    - 11

  draw: #ドロー3~7のcsm
    - 20
    - 21
    - 22
    - 23
    - 24

  spcards:
    1: #ドロー?
      enable: true
      csm: 0
      chance: 100
    2: #リムーブ
      enable: true
      csm: 33
      chance: 100
    3: #リターン
      enable: true
      csm: 34
      chance: 100
    4: #エクスチェンジ
      enable: true
      csm: 25
      chance: 100
    5: #パーフェクトドロー
      enable: true
      csm: 31
      chance: 80
    6: #パーフェクトドロー+
      enable: true
      csm: 32
      chance: 75
    7: #アルティメットドロー
      enable: true
      csm: 39
      chance: 75
    8: # ベットアップ1
      enable: true
      csm: 13
      chance: 100
    9: #ベットアップ2
      enable: true
      csm: 14
      chance: 100
    10: #ベットアップ2+
      enable: true
      csm: 15
      chance: 100
    11: #シールド
      enable: true
      csm: 35
      chance: 100
    12: #シールド+
      enable: true
      csm: 36
      chance: 100
    13: #spチェンジ
      enable: true
      csm: 37
      chance: 80
    14: #spチェンジ+
      enable: true
      csm: 38
      chance: 75
    15: #ゴール17
      enable: true
      csm: 26
      chance: 100
    16: #ゴール24
      enable: true
      csm: 27
      chance: 100
    17: #ゴール27
      enable: true
      csm: 28
      chance: 100
    18: #デストロイ
      enable: true
      csm: 17
      chance: 100
    19: #デストロイ+
      enable: true
      csm: 18
      chance: 100
    20: #デストロイ++
      enable: true
      csm: 19
      chance: 75
    21: #ラブ・ユア・エネミー
      enable: true
      csm: 30
      chance: 100
    22: #ハーヴェスト
      enable: true
      csm: 29
      chance: 50
    23: #デスぺレーション
      enable: true
      csm: 16
      chance: 50

mode: false